name = "tac-orchestrator-worker"  # ez lehet a modulok összegző neve is
main = "src/worker.js"
compatibility_date = "2024-09-01"
account_id = "78039e8d47685cac3bcd449127cee221"
workers_dev = true

[vars]
# ide tehetsz fix env változókat, ha akarsz (nem a secret kulcsot)

# OpenAI kulcs secretként:
# futtasd majd: wrangler secret put OPENAI_API_KEY